[book]
title       = "reptr"
description = "Local-first pentest report generator"
authors     = ["vral-parmar"]
language    = "en"
src         = "src"

[output.html]
site-url         = "/reptr/"
no-section-label = true
additional-css   = ["custom.css"]

[output.html.fold]
enable    = true
level     = 1
